version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: zpantry_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#Khoa2003
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    container_name: zpantry_api
    build:
      context: .
      dockerfile: ZPantry_Backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Cấu hình sẵn chuỗi kết nối Database trỏ sang container SQL Server
      - ConnectionStrings__DefaultConnection=Server=database;Database=ZPantryDb;User Id=sa;Password=#Khoa2003;TrustServerCertificate=True;

volumes:
  sql_data:
