<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="Repositories\Inmplementations\" />
    <Folder Include="Repositories\Entities\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Services\Implementations\" />
  </ItemGroup>

</Project>
